# Generated by Django 4.1.2 on 2022-10-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('gas', models.FloatField()),
                ('dp', models.FloatField()),
                ('nf', models.FloatField()),
                ('nf_plus', models.FloatField()),
                ('nt', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
